name: unifi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: debian-buster

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker push spl147/unifi:lateste:$(date +%s)
